config/routes.rb
FoursquareSearch::Application.routes.draw do

  resources :users, only: [] do
    resources :favourites, only: [:index]
  end

  # Callback URL from Foursquare
  match 'auth/:provider/callback', to: 'sessions#create'

  # Failure URL
  match 'auth/failure', to: redirect('/')

  # Destroy the session on sign out
  match 'signout', to: 'sessions#destroy', as: 'signout'

  # Allow post to search venues
  post 'search', to: 'venues#search', as: 'search'

  # Favourite a venue
  post 'favourite', to: 'venues#favourite', as: 'favourite'

  root :to => 'venues#index'
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  attr_accessible :user_id, :venue_id
  belongs_to :venue, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :first_name, :provider, :uid, :last_name, :email
  has_many :favourites
  has_many :venues, through: :favourites

  def self.from_omniauth(auth)
    where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.first_name = auth["info"]["first_name"]
      user.last_name = auth["info"]["last_name"]
      user.email = auth["info"]["email"]
    end
  end

  def has_favourite_venue?(venue_id)
    !favourites.where(venue_id: venue_id).empty?
  end

  def toggle_favourite(venue)
    if has_favourite_venue?(venue.venue_id)
      favourites.find_by_venue_id(venue.venue_id).destroy
      return false
    else
      venues << venue
      return true
    end
  end

end

app/models/venue.rb
require 'csv'

class Venue < ActiveRecord::Base
  attr_accessible :venue_id, :canonical_url, :name, :categories, :address, :city, :country, :distance
  has_many :favourites
  has_many :users, through: :favourites

  self.primary_key = :venue_id

  def self.from_search_venue(hash_object)
    venue = Venue.new
    venue.venue_id = hash_object.id
    venue.canonical_url = hash_object.canonicalUrl
    venue.name = hash_object.name
    venue.categories = hash_object.categories.map{|category| category.name }.join(', ')
    venue.address = hash_object.location.address
    venue.city = hash_object.location.city
    venue.country = hash_object.location.country
    venue.distance = hash_object.location.distance
    venue
  end

  def self.clear_cached_venues
    $redis.del 'venues'
  end

  def self.cache_venue(venue)
    $redis.hmset 'venues', venue.venue_id, venue.to_json
  end

  def self.get_venue(id)
    JSON.parse($redis.hget 'venues', id)
  end

  def self.find_or_create(id)
    venue = Venue.find_by_venue_id(id)
    return venue unless venue.nil?
    venue = Venue.new(Venue.get_venue(id))
    venue.save
    venue
  end

  def self.to_csv(venue_list)
    columns = Venue.attribute_names
    CSV.generate do |csv_data|
      csv_data << columns
      venue_list.each do |venue|
        csv_data << venue.attributes.values_at(*columns)
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController

  respond_to :html, :csv

  def index
    @venues = User.find(params[:user_id]).venues
    respond_to do |format|
      format.html
      format.csv {
        send_data Venue.to_csv(@venues)
      }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

  respond_to :html, :json, :js

  def index
  end

  def search
    term = params[:search]
    @venues = []
    Venue.clear_cached_venues
    $foursquare.search_venues(term).each do |search_venue|
      venue = Venue.from_search_venue(search_venue)
      Venue.cache_venue(venue)
      @venues << venue
    end
  end

  def favourite
    if current_user
      venue = Venue.find_or_create(params[:venue_id])
      favourite = current_user.toggle_favourite(venue)
      render json: { favourite: favourite }
    else
      head 401
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/venues_helper.rb
module VenuesHelper

  def favourite_link(user, venue_id)
    if user
      klass = user.has_favourite_venue?(venue_id) ? "icon-star" : "icon-star-empty"
      link_to (content_tag :i, "", 'class' => klass), '#', class: "favourite", 'data-id' => venue_id
    else
      content_tag :p, "?"
    end
  end

end

app/views/favourites/index.html.erb
<div id="favourites-list">
  <% if @venues.empty? %>
    <p class="center">No favourites yet</p>
  <% else %>
    <%= render 'venues/headline' %>
    <%= render @venues %>
    <br/>
    <div class="center"><%= link_to "export (csv)", user_favourites_path(current_user, format: :csv) %></div>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">Foursquare Search</a>
      <div class="nav-collapse collapse navbar-responsive-collapse">
        <ul class="nav pull-right">
          <% if current_user %>
            <li><%= link_to "Welcome, #{current_user.first_name}!", "/" %></li>
            <li><%= link_to "Favourites", user_favourites_path(current_user) %></li>
            <li><%= link_to "Sign out", signout_path %></li>
          <% else %>
            <li><%= link_to "Sign in with Foursquare", "/auth/foursquare" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foursquare Search</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/venues/_headline.html.erb
<div class="row table-header">
  <div class="span1">Favourites</div>
  <div class="span2">Venue name</div>
  <div class="span3">Category</div>
  <div class="span4">Address</div>
  <div class="span2">Distance (meters)</div>
</div>

app/views/venues/_search.html.erb
<%= form_tag search_path, remote: true, id: 'search-form' do %>
  <div class="input-append">
    <%= text_field_tag :search, params[:search], id: "search-input", class: "span3", placeholder: "e.g. starbucks" %>
    <%= submit_tag "Search", class: "btn", disable_with: "Please wait..." %>
  </div>
<% end %>

app/views/venues/_venue.html.erb
<div class="row">
  <div class="span1"><%= favourite_link(current_user, venue.id) %></div>
  <div class="span2"><%= link_to venue.name, venue.canonical_url, target: "_blank" %></div>
  <div class="span3"><%= venue.categories %></div>
  <div class="span4"><%= "#{venue.address}, #{venue.city}, #{venue.country}" %></div>
  <div class="span2"><%= venue.distance %>m</div>
</div>

app/views/venues/index.html.erb
<div class="row">
  <div class="span4 offset4 center">
    <h4>Search for venues on foursquare</h4>
    <%= render 'venues/search' %>
  </div>
</div>

<% unless current_user %>
  <div class="row">
    <div class="span4 offset4 center">(<%= link_to "sign in with foursquare", "/auth/foursquare" %> to favourite venues)</div>
  </div>
<% end %>

<div id="search-results"></div>